### ISSUE TITLE
Data Challenge:  Software Packaging:  Get Workflow system clients into CVMFS

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#111]
get the workflow system clients into CVMFS if necessary.

**Comment by Andrew-McNab-UK** [comment]
It would be good to get the workflow command used by people into cvmfs. However, it is a single Python3 with no dependencies beyond the default Python3 modules so it is also realistic for people to get it straight from GitHub. 

All of the scripts needed inside jobs are included in the Generic Jobs scripts submitted to jobsub and shouldn't go in cvmfs.

**Comment by StevenCTimm** [comment]
Now superseded by issue #242
