### ISSUE TITLE
Data Challenge: Network access: Test transatlantic CERN-FNAL link

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#113]
Make sure all routings between  FNAL DCACHE and CERN EOS are symmetric and going on the dedicated
network circuits as they should be.  Try to test bandwidth to see if we can get expected bandwidth.
(Hard because we can't log onto the actual EOS machines to run iPerf, etc.)

**Comment by sfuess** [comment]
iperf3 tests show data following the expected ESNET path.  ESNET successfully fixed the "direction" of the data flow in their monitoring.  The monitor of the OSCARS path is at https://my.es.net/oscars/view/P6FG
We have a 10 Gb bandwidth guarantee on that path, extra as available.  Failover is to the LHCOPN path.

With a single iperf3 server at CERN only say ~ 5 Gb/s max in either direction.  To do is trying multiple file transfers (outside of the Rucio transfers) to stress bandwidth.
