### ISSUE TITLE
Data Challenge: Rucio: Test functionality from within worker node job

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#123]
Including rucio list-file-replicas, rucio download, and if necessary rucio upload.

**Comment by Andrew-McNab-UK** [comment]
The Workflow System currently assumes that a working rucio command that can do rucio upload is provided, either from cvmfs or as a recipe for setting up rucio inside the job (we have produced a recipe that does this but there are missing gfal2 dependencies which prevent uploads.)

**Comment by StevenCTimm** [comment]
rucio client now in CVMFS and mostly working, still have to deal with corner cases at some sites.
