### ISSUE TITLE
Data Challenge: Workflow System:  Detect new incoming runs and submit workflow requests

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#130]
Identify what is necessary to detect newly created files and submit workflow requests (and generic jobs) to
process them via the workflow allocator

**Comment by Andrew-McNab-UK** [comment]
The current state of the Workflow System is that requests can optionally be created with settings to requery MetaCat to find any new files, at a given frequency and for a given amount of days. Requests have an MQL expression which is used to find their input files, which could specify data from a specific time period too. So, to a simple script could use the workflow command to submit a series of requests with appropriate time ranges in the MQL and frequencies/durations in the workflow settings.
