### ISSUE TITLE
Data Challenge: Scope Document --Merge and finalize the wording

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#145]
Merge the two documents (for pipeline and processing) and get signoff of DM, WF, and Prod groups + HMS/MK/AMcN

**Comment by dougbenjamin** [comment]
Merged the information from this document - ["Production Portion of ProtoDUNE II data challenge"](https://docs.google.com/document/d/1twwU9oTUCXxxwZIHTqGUe0MwiueZNZivef59awnqNj8/edit?usp=sharing)

Into the document : ["Scope for ProtoDUNE II Data Challenge"](https://docs.google.com/document/d/1dtFxDV7RwU2RGSQkR5xJqWDc-bkLTTuE-FDt9v74_pI/edit?usp=sharing)
