### ISSUE TITLE
Data Challenge: At the submission step (POMS or Workflow Allocator) test communication with MetaCat

### ISSUE THREAD

**Issue by dougbenjamin** [DUNE/data-mgmt-ops#148]
Make sure that the submission step, whether POMS or WA, can talk to MetaCat (separate from the wrapper script inside the job).

**Comment by Andrew-McNab-UK** [comment]
For the Workflow System, this is done by the wfs-finder agent which runs every minute, picks up any new requests and uses their MQL expressions to query MetaCat using its REST API to get the list of input files. So from the users point of view, they submit the request with the workflow command and wait a couple of minutes to see what becomes visible to the command (workflow show-files --request-id NNNN) or the web dashboard.

**Comment by StevenCTimm** [comment]
This is now a question for poms-metacat-data dispatcher use case.
