### ISSUE TITLE
Data Challenge: Make dashboard with links to all the new monitoring devices.

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#154]

**Comment by hschellman** [comment]
This is actually here as  https://github.com/DUNE/data-mgmt-ops/issues/140. already so we might want to consolidate

**Comment by hschellman** [comment]
https://docs.google.com/document/d/1HWwvmL0nZLtM8dU6-hVATqdQ9MBON6_1oisJLUOPExw/edit?usp=sharing is a first try at this.

**Comment by hschellman** [comment]
One issue still here - the elf link is inaccessible due to certificate issues.  We might want some docs on getting all the certs you need.  I thought I had CERN certs. may have to redo.

**Comment by StevenCTimm** [comment]
This has now been superseded by issue #241
