### ISSUE TITLE
Data Challenge: Data Dispatcher:  hook up to ElasticSearch

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#156]
similar to what sam web ui does.

**Comment by ivmfnal** [comment]
Need the documentation on how to put data into Elastic Search

**Comment by StevenCTimm** [comment]
There is an example of how to do it in this piece of code:

https://github.com/DUNE/data-mgmt-ops/blob/master/container_info.py

Basically it is using Kafka as an input device. To actually get the Kafka queue into elasticsearch then, we have to file a ticket with Kevin Retzke's group and he has to vet the contents of the Kafka queue.

**Comment by StevenCTimm** [comment]
Now superseded by #246
