### ISSUE TITLE
Data Challenge: Declaration Daemon:  Come up with an interim plan to use for the data challenge

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#158]
Reworking of Fermi-FTS to support python3, MetaCat, and Rucio, won't be done by this time.

Steve writing the requirements for an interim daemon now.

**Comment by StevenCTimm** [comment]
Requirements at https://docs.google.com/document/d/1awfWZ8zd8QdT8TrizFDmmSfWT0NwFDhsBmpmRDKyK28/edit#

Discussions with Igor Mandrichenko, he thinks he can write something like that

**Comment by ivmfnal** [comment]
Will use Data Dispatcher native event, data item names until we come up with common naming schema
