### ISSUE TITLE
Data Challenge:  Make OSG 3.6 based singularity container

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#160]
To include Rucio clients, osg 3.6 clients plus the extra rpms from epel that used to be in osg 3.5 
(plus gfal2-2.20 and all plugins)

**Comment by StevenCTimm** [comment]
OSG 3.6 container already exists in singularity--try in the VM to see if it works there

**Comment by kherner** [comment]
We're also updating the default FNAL worker node Singularity image to use OSG 3.6 next week. All testing so far has been without incident.
