### ISSUE TITLE
Data Challenge:  Workflow Allocator:  hook up to ElasticSearch

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#161]
Hook up file delivery data from the WorkFlow Allocator to ElasticSearch so we can get performance data
on throughput similar to what SAM provides.

**Comment by Andrew-McNab-UK** [comment]
We need a list of events to send (same list as SAM sends?) and what the endpoint in front of ElasticSearch looks like. Can we get a test system to develop against?

**Comment by hschellman** [comment]
check out https://docs.google.com/document/d/1DZtOECpQlc9owNUqIbpOZ7Q5bxoeo7pXSCrP7cFf8qE/edit?usp=sharing for a list of the fields we need.  The script running on the remote node will need to add a few fields.

**Comment by StevenCTimm** [comment]
Now superseded by #247
