### ISSUE TITLE
Data Challenge: Test rucio upload to all RSE's

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#168]
Part of the data challenge involves trying to read from the nearest RSE and then write output back to that same RSE using Rucio upload.  Therefore we have to check  to make sure rucio upload is working
for all of them.. all the disk RSE anyway.

**Comment by wyuan-uoe** [comment]
I'm testing `rucio upload` for `DUNE_ES_PIC, DUNE_FR_CCIN2P3_DISK, NIKHEF, SURFSARA, PRAGUE, LANCASTER, MANCHESTER, QMUL, RAL_ECHO, RAL-PP, DUNE_US_BNL_SDCC`

`SURFSARA` is not ready yet. No protocol in Rucio for `DUNE_ES_PIC`.

For the other RSEs, I've tested `rucio upload` with all the possible protocols listed in Rucio, one by one.

`NIKHEF, PRAGUE, RAL_ECHO, RAL-PP, DUNE_US_BNL_SDCC` work successfully with all their possible protocols.

For `DUNE_FR_CCIN2P3_DISK`, `https` works. `xrootd` returns an error:
```
File "/dune/app/home/dunepro/rucio126_python3/lib64/python3.6/site-packages/rucio/rse/protocols/gfal.py", line 498, in __gfal2_exist
    if ctx.stat(str(path)):
gfal2.GError: Failed to stat file (Permission denied)
```
`gfal-copy` interactively using `xrootd` can work, however.

For `LANCASTER`, `https` works. `xrootd` returns an error:
```
Details: Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [3010] Opening relative path 'dpm/lancs.ac.uk/home/dune/dc4-output/d2/48/testfile2?oss.asize=20971520&xrd.gsiusrpxy=/opt/dunepro/dunepro.Production.proxy&xrd.wantprot=gsi,unix' is disallowed. (destination)
```
`gfal-copy` interactively using `xrootd` can work as well.

For `MANCHESTER`, only `https` can work. `xrootd, gsiftp` return the errors like `DUNE_FR_CCIN2P3_DISK` xrootd error.

For `QMUL`, all protocols got access problem.

**Comment by StevenCTimm** [comment]
Fixes have been made at QMUL since this work was done so QMUL should be retried.
We should work with one of the sites for which xrootd is failing, Manchester for instance, and see what's happening there. 
DUNE_ES_PIC now has protocols added too, although it's not critical for data challenge
catching RSE.

the "opening relative path is disallowed" error is a config error.
All of our RSE's have just one / in the path rather than two.  
FTS3 is smart enough to add the extra // between the hostname:port and the path.
But it appears that rucio upload is not.
BUT if we add // in every single root protocol in the RSE thing then FTS3 breaks and doesn't do it right.

**Comment by wyuan-uoe** [comment]
`DUNE_ES_PIC` and `SURFSARA` work now.

**Comment by Andrew-McNab-UK** [comment]
I've gone through the list again and put what works for me with my DN and the Production role in the Workflow System database table for storages, with a summary here: https://wfs.dune.hep.ac.uk/dashboard/?method=list-storages 

Nine worked, either with root (Workflow's default) or with https, which has to be put in the database by hand at the moment. The two exceptions were QMUL and MANCHESTER. 

I also tried DUNE_US_FNAL_DISK_STAGE just now and got errors with both root and https.

My X.509/VOMS details during the tests:

dunegpvm15.amcnab: voms-proxy-info -all
subject   : /DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Andrew McNab/CN=UID:amcnab/CN=1280639127/CN=3907649102
issuer    : /DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Andrew McNab/CN=UID:amcnab/CN=1280639127
identity  : /DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Andrew McNab/CN=UID:amcnab/CN=1280639127
type      : RFC compliant proxy
strength  : 2048 bits
path      : /tmp/x509up_u54145
timeleft  : 9:57:46
key usage : Digital Signature, Key Encipherment, Data Encipherment
=== VO dune extension information ===
VO        : dune
subject   : /DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Andrew McNab/CN=UID:amcnab
issuer    : /DC=org/DC=incommon/C=US/ST=Illinois/O=Fermi Research Alliance/OU=Fermilab/CN=voms2.fnal.gov
attribute : /dune/Role=Production/Capability=NULL
attribute : /dune/Role=NULL/Capability=NULL
timeleft  : 11:30:16
uri       : voms2.fnal.gov:15042
