### ISSUE TITLE
Ops:  apparently no shared 3rd party copy between RAL-PP and QMUL

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#181]
FTS3 has thus far shown no transfers between RAL-PP and QMUL even though the full contents of RAL-PP have been set up to be transferred to QMUL.  Instead Rucio seems to be trying to pull the lot off of tape at Fermilab.
RAL-PP
Protocols:
==========
  gsiftp
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 1, "write": 2, "delete": 2, "third_party_copy": 1}}'
    extended_attributes: None
    hostname: mover.pp.rl.ac.uk
    impl: rucio.rse.protocols.gfalv2.Default
    port: 2811
    prefix: /pnfs/pp.rl.ac.uk/data/dune
    scheme: gsiftp
  https
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 2, "write": 1, "delete": 1, "third_party_copy": 1}}'
    extended_attributes: None
    hostname: mover.pp.rl.ac.uk
    impl: rucio.rse.protocols.gfalv2.Default
    port: 2880
    prefix: /pnfs/pp.rl.ac.uk/data/dune
    scheme: https
  root
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 1, "write": 0, "delete": 0, "third_party_copy": 1}}'
    extended_attributes: None
    hostname: mover.pp.rl.ac.uk
    impl: rucio.rse.protocols.gfalv2.Default
    port: 0
    prefix: /pnfs/pp.rl.ac.uk/data/dune
    scheme: root
  srm
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 3, "write": 3, "delete": 3, "third_party_copy": 1}}'
    extended_attributes: {'web_service_path': '/srm/managerv2?SFN='}
    hostname: heplnx204.pp.rl.ac.uk
    impl: rucio.rse.protocols.gfalv2.Default
    port: 8443
    prefix: /pnfs/pp.rl.ac.uk/data/dune
    scheme: srm

QMUL

==========
  davs
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 2, "write": 2, "delete": 2, "third_party_copy": 1}}'
    extended_attributes: None
    hostname: se03.esc.qmul.ac.uk
    impl: rucio.rse.protocols.gfalv2.Default
    port: 8443
    prefix: /dune/RSE
    scheme: davs
  srm
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 1}}'
    extended_attributes: {'web_service_path': '/srm/managerv2?SFN='}
    hostname: se03.esc.qmul.ac.uk
    impl: rucio.rse.protocols.gfalv2.Default
    port: 8444
    prefix: /dune/RSE
    scheme: srm

**Comment by StevenCTimm** [comment]
Now seeing a few successful davs->davs 3rd party transfers. 

srm->srm being attempted and failing
gridftp->srm also being attempted and failing.

srm input on QMUL is known to work from other sites.

**Comment by StevenCTimm** [comment]
[TRANSFER [13] TRANSFER globus_ftp_client: the server responded with an error 530 530-Login incorrect. : globus_gss_assist: Error invoking callout 530-globus_callout_module: The callout returned an error 530-an unknown error occurred 530 End.](https://fts3-public.cern.ch:8449/fts3/ftsmon/#/transfers?state=FAILED&vo=dune&source_se=gsiftp%3A%2F%2Fmover.pp.rl.ac.uk&dest_se=srm%3A%2F%2Fse03.esc.qmul.ac.uk&reason=TRANSFER%20%5B13%5D%20TRANSFER%20%20globus_ftp_client%3A%20the%20server%20responded%20with%20an%20error%20530%20530-Login%20incorrect.%20%3A%20globus_gss_assist%3A%20Error%20invoking%20callout%20%20530-globus_callout_module%3A%20The%20callout%20returned%20an%20error%20%20530-an%20unknown%20error%20occurred%20%20530%20End.%20%20%20&time_window=1)

That's the gsiftp to srm error

Same error in srm to srm.
Davs to davs is fine.

**Comment by wyuan-uoe** [comment]
I deleted QMUL `root` protocol for few days when testing `rucio upload` stuff. Now I add it back.

**Comment by StevenCTimm** [comment]
Copies started up soon after wenlong added the root protocol back.. we are still seeing the gsiftp to gsiftp errors   Some davs to davs copying going well too.   transfers in aggregate about 95% done.. taking slower than normal because srm is preferred protocol and much more transfers being tried that way first and failing.

**Comment by StevenCTimm** [comment]
QMUL now fixed the gsiftp errors too.  Closing this.
