### ISSUE TITLE
Data Management: Need to show old RSE's as disabled

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#190]
Edinburgh, Liverpool, Imperial, DUNE_FR_CCIN2P3

**Comment by StevenCTimm** [comment]
Have marked them (all but Liverpool) disabled... will hold this open since I want to turn off a few FNAL ones too

**Comment by Andrew-McNab-UK** [comment]
I think there needs to be a way to mark which RSEs are gone and should be ignored which is separate from the availability_delete/_read/_write settings. (Maybe there is?) I can make the WTF tests ignore RSEs which have gone but carry on testing RSEs which are not available for reading and writing. The use case is that an RSE goes into downtime and gets marked as unavailable but you want the daily tests to continue so you can see if it's working properly before re-enabling it.

**Comment by StevenCTimm** [comment]
Have picked the decommissioned=True setting to mark all rse's which are gone and not coming back
