### ISSUE TITLE
Onboard RAL-PP

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#2]
srm://heplnx204.pp.rl.ac.uk/pnfs/pp.rl.ac.uk/pnfs/pp.rl.ac.uk/data/dune
gsiftp://mover.pp.rl.ac.uk//pnfs/pp.rl.ac.uk/pnfs/pp.rl.ac.uk/data/dune
root://mover.pp.rl.ac.uk//pnfs/pp.rl.ac.uk/pnfs/pp.rl.ac.uk/data/dune

We have 200TB allocated.

**Comment by wyuan-uoe** [comment]
Fix the url:

srm://heplnx204.pp.rl.ac.uk//pnfs/pp.rl.ac.uk/data/dune
gsiftp://mover.pp.rl.ac.uk//pnfs/pp.rl.ac.uk/data/dune
root://mover.pp.rl.ac.uk//pnfs/pp.rl.ac.uk/data/dune

**Comment by StevenCTimm** [comment]
Closing  this one as it was a duplicate of issue #1
