### ISSUE TITLE
Regularize the protocol priorities on all Rucio RSE

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#228]
xrootd should be high priority for reads on lan and wan

writes lan and wan https/davs should be priority.

3rd party copy https/davs should be high priority

gsiftp needed for 3rd party transfers outbound from Fermilab until we get srm/https deployed.

**Comment by StevenCTimm** [comment]
Should never have any tied or equal priorities anywhere.

Contact sites if xrootd isn't working.

**Comment by dougbenjamin** [comment]
when can we drop gsiftp?

**Comment by dougbenjamin** [comment]
what about srm protocol?

**Comment by dougbenjamin** [comment]
have regularized the protocol priorities for all RSE except FNAL ones.

**Comment by dougbenjamin** [comment]
except that Rucio did not keep the priorities correct.

**Comment by StevenCTimm** [comment]
Mostly done but a couple https ones sitting out there parallel to davs.

**Comment by StevenCTimm** [comment]
We still have some sites which have both https and davs defined, the https should now be deleted.

**Comment by StevenCTimm** [comment]
OK https now deleted everywhere.  xrootd shown as secondary third party copy everywhere
gsiftp has to stay on FNAL_DCACHE and DUNE_US_FNAL_DISK_STAGE so we can talk to NERSC.

Closing this.
