### ISSUE TITLE
Beam Readiness:  Hook data dispatcher up to ElasticSearch

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#246]

**Comment by ivmfnal** [comment]
See https://github.com/DUNE/data-mgmt-ops/blob/master/container_info.py as an example

**Comment by StevenCTimm** [comment]
This is now not critical for DUNE but people will still have to do it for the other experiments that use the DD

**Comment by StevenCTimm** [comment]
This is moot for dune, closing this.
