### ISSUE TITLE
get SRR records enabled for all UK sites, 

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#26]

**Comment by wyuan-uoe** [comment]
I got the SRR info for `RAL-PP, RAL_ECHO, LIVERPOOL, LANCASTER, MANCHESTER`, those are DPM sites, very trivial for  SRR info. I was noticed `QMUL and IMPERIAL` not having SRR available yet, which are STORM and dcache sites.

With the SRR info, I plot the sites allocations as:
http://tatties.ph.ed.ac.uk:5601/goto/1eb06af0e8e5d86e1bfc4f4a698aa68d

I will investigate all RSE sites.

**Comment by wyuan-uoe** [comment]
Also get SRR for NIKHEF, a dCache site.

**Comment by wyuan-uoe** [comment]
Now SRR for all UK sites can work.

**Comment by StevenCTimm** [comment]
Wenlong continues to get more SRR records but closing this for now.
