### ISSUE TITLE
ifdh mkdir doesn't work from BNL

### ISSUE THREAD

**Issue by hschellman** [DUNE/data-mgmt-ops#261]
I'm trying to do ifdh mkdir in jobs at BNL - the job runs fine but no output comes back. 

/dune/data/users/schellma/log/64993869.9@jobsub02.fnal.gov logs show this issue.  

Look for BNL in the files in that directory as it ran across a lot of other sites (and worked).

**Comment by StevenCTimm** [comment]
This problem has been reported several times previously at BNL--we may have to request assistance from the GWMS factory operations at SDSC and get the details of the glidein logs.. one of the few explanations is that it could be that one of the htcondor-ce at BNL is different from the others and throws a bad configuration in there, possibly a non-standard singularity image.

**Comment by StevenCTimm** [comment]
core cause seems to be that ifdh was unsetting the GFAL_CONFIG_DIR  but not the GFAL_PLUGINS_DIR and thus
we were pointing at the config directory in CVMFS but the plugins in singularity, which did not match.  Config dir called for a gsiftp plugin which isn't in our singularity container, thus the error message.

**Comment by StevenCTimm** [comment]
And  it follows that at BNL and only at BNL they were sourcing the OSG worker node client setup out of CVMFS
even though we haven't been able to prove how and where it happened.

**Comment by dougbenjamin** [comment]
Hi,

  It appears that DUNE jobs go into two different account depending on the farm. Need to know which nodes the jobs fail and then we can tell which farm is affected.

From: Steven Timm ***@***.***>
Reply-To: DUNE/data-mgmt-ops ***@***.***>
Date: Thursday, January 26, 2023 at 4:08 PM
To: DUNE/data-mgmt-ops ***@***.***>
Cc: Doug Benjamin ***@***.***>, Assign ***@***.***>
Subject: Re: [DUNE/data-mgmt-ops] ifdh mkdir doesn't work from BNL (Issue #261)


core cause seems to be that ifdh was unsetting the GFAL_CONFIG_DIR but not the GFAL_PLUGINS_DIR and thus
we were pointing at the config directory in CVMFS but the plugins in singularity, which did not match. Config dir called for a gsiftp plugin which isn't in our singularity container, thus the error message.

**Comment by StevenCTimm** [comment]
BNL has changed the user under which DUNE jobs run on the shared cluster and now further failures appear to have gone away.  (now we run as "fermipro"). 

will hold this open for a bit until we see it again.

**Comment by dougbenjamin** [comment]
no further error reports after the change made.
