### ISSUE TITLE
CERN_PDUNE_CASTOR prefixes are wrong

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#269]
can read existing files from there but writes fail
because they are trying to write into /eos/experiment/neutplatform/protodune top level.
Early test with scope "test" worked because we tried to write to 
/eos/experiment/neutplatform/protodune/test directory, which happened to exist.

Should be pointing at /eos/experiment/neutplatform/protodune/rawdata/np04
but that's tricky because there's also stuff in there from /eos/experiment/neutplatform/protodune/rawdata/np02
Not clear how we do this.

We don't intend to write much more into that RSE anyway but we should sort this out. .may have similar problem on CTA should check.

**Comment by wyuan-uoe** [comment]
https://eospublic.cern.ch//eos/public/proc/accounting has the details how they set the subdirs under /eos/experiment/neutplatform/protodune, and which chargegroup for each subdirs.

**Comment by StevenCTimm** [comment]
I've asked in Rucio support and will raise this with the developers tomorrow at our meeting with them.
We are only seeing this now because I only enabled the RSE in question for writing a couple days ago.

**Comment by StevenCTimm** [comment]
As I suspected the same applies to CERN_PDUNE_CASTOR
Have asked Brandon to verify what's in the DB.. probably the right way to approach this is with database-fu.

**Comment by StevenCTimm** [comment]
Martin Baritsis confirms database-fu is the right way to go for this.

**Comment by StevenCTimm** [comment]
Have opened https://cern.service-now.com/service-portal?id=ticket&is_new_order=true&table=u_request_fulfillment&sys_id=15c3a13e877c2510094a65770cbb35e2
to see if it is possible to make symlinks in CTA.    CERN ticket RQF2229458

IF so then we could make the data currently available under rawdata/np02 be visible in rawdata/np04 and everything would be fine (after we do the database-fu).

**Comment by StevenCTimm** [comment]
CERN confirms we can make symlinks in CTA.  I did it (using the eos ln command) and it worked.

The Fermilab side of this is tracked in RITM1120141

**Comment by StevenCTimm** [comment]
Brandon fixed all the paths this morning.  We can make rules that source from CERN_PDUNE_CASTOR and they work.
We have attempted to make rules that go to CERN_PDUNE_CASTOR.  These do not work yet.  It appears that it is because the current Rucio daemon DN is not accepted by CTA.  Have filed incident with CERN to add the DN.
Once that's done we have to do the same to FNAL_DCACHE.

**Comment by StevenCTimm** [comment]
Fixed.
