### ISSUE TITLE
Decide on the name/structure of the data lifetimes in metacat

### ISSUE THREAD

**Issue by hschellman** [DUNE/data-mgmt-ops#271]
We just need to decide on the schema

I see something like

retention.class = string  (test, commissioning, data, reco, sim, user...)
retention.startdate = timestamp (when the clock starts) 
retention.diskdate = timestamp
retention.tapedate = timestamp
retention.diskstatus = string (active, pending, inactive, gone)
retention.tapestats = string (active, pending, inactive, gone) 

where the class determines the official lifetimes

**Comment by StevenCTimm** [comment]
see heidi's document 

https://dune.github.io/DataCatalogDocs/index.html#

This was discussed at Feb 21 DUNE data management meeting and was found to be acceptable by all who were there.

the final version does not have a retention.diskdate or retention.tapedate or retention.diskstatus or retention.tapestatus.

Rather it just has

        "retention.status": "active",
        "retention.class": "physics"

**Comment by StevenCTimm** [comment]
retention.status is defined to be either active, retiring, retired
retention.class is defined, other, test, study, physics, simulation, rawdata
