### ISSUE TITLE
Rucio bug:  apparently when one protocol is removed from the RSE rucio ups the priorities of the other protocols to fill in the gaps

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#272]
We should try using the python API to get around this and see if we can change the priorities on the fly.
Have already notified Rucio devs on this one.  Rucio developers confirm that the code works this way now but 
admit it is a bug, not an intended feature.

**Comment by StevenCTimm** [comment]
Doug is going to work with Brandon/Dennis to change the priorities in the database for now.
But we will continue to also follow this up with the rucio devs.

**Comment by bjwhite-fnal** [comment]
I opened an issue in the Rucio Github to hopefully address this.
https://github.com/rucio/rucio/issues/6083

**Comment by StevenCTimm** [comment]
Rucio developers say they will take out the automatic reordering it is causing too many problems.

**Comment by StevenCTimm** [comment]
according to rucio devs this is now fixed.
