### ISSUE TITLE
Behavior of DUNE path generator when only date available is the metacat create date

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#297]
Current DUNE privilege package picks the year from either the start date, stop date, or metacat creation date 
in MetaCat.  But DeclaD needs to construct the path first and check the existence of the file before declaring it to metacat, and we have found a class of files for which start time and stop time don't exist in the metadata.  Have to clear this with James Perry to make sure we agree on the convention of what to do.  

Any files which may have been declared this way already are ok because the path as constructed, whatever it is, is captured in th e replica database.. but we need to know for new files once the DeclaD starts running on top of tape-backed dCache.

**Comment by jamesp-epcc** [comment]
If the start time and stop time don't exist, the path generator will use the MetaCat creation date as noted. However, only the year is used so the granularity doesn't have to be too fine. If DeclaD simply uses the current year in these cases and then the file is declared to MetaCat before the year changes, everything should work. If the year changes before the file is declared to MetaCat then the path used in Rucio will not match the path checked by DeclaD. This will happen very rarely, I'm not sure what the right answer is in those cases. These files could be corrected manually. Or DeclaD could be programmed to back off and try again if the year changes between the check and the declaration.

**Comment by StevenCTimm** [comment]
So yes I think we've observed this happening now with files that are coming out of the DAQ and we've observed that it does the expected thing.  There is no further action needed on this, we are ok with the privilege package as implemented in this regard.
__
