### ISSUE TITLE
New DN for dunepro managed proxy

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#300]
have added it to Rucio, filed a ticket to get it added at CERN, and asked Ken to add it to NERSC.

**Comment by dougbenjamin** [comment]
What is the current DN?

**Comment by StevenCTimm** [comment]
Current (new) one /DC=org/DC=incommon/C=US/ST=Illinois/O=Fermi Research Alliance/CN=dunepro-dunegpvm01.fnal.gov

it was 
/DC=org/DC=incommon/C=US/ST=Illinois/O=Fermi Research Alliance/OU=Fermilab/CN=dunepro-dunegpvm01.fnal.gov
