### ISSUE TITLE
Transfers to SURFSARA are failing

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#340]
Transfer to SURFSARA are failing, with 507 (not enough space). have to investigate.

**Comment by wyuan-uoe** [comment]
From SRR, SURFSARA allocated 25TB for DUNE, and we've used 25TB already.
https://dcacheview.grid.surfsara.nl:22884/api/v1/srr

I don't remember SURFSARA plan, to set a larger allocation numbers to DUNE.

**Comment by StevenCTimm** [comment]
have E-mailed surfsara admins will see what we get.. no response yet.

**Comment by StevenCTimm** [comment]
SURFSara say that the limit is now 756TB, I have configured that appropriately and failures have stopped.
