### ISSUE TITLE
Get rucio to submit multi-file jobs to FTS3

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#392]
CMS and ATLAS do it already, can't be hard.

**Comment by StevenCTimm** [comment]
default in 1.32 and 1.33 in multiple files check conveyor-submitters.

**Comment by StevenCTimm** [comment]
yuyi guo is working with other vo's incl Rubin to make this happen, good project for her to investigate.

**Comment by bjwhite-fnal** [comment]
This is done.

**Comment by StevenCTimm** [comment]
Thanks Brandon, looks good, closing.
