### ISSUE TITLE
Test new xrootd head node at CC_IN2P3

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#4]
From Elisabetta Pennacchio:  (lead NP02 computing contact)

Hi Steve,
last week, a storage xrootd server has been setup at CCIN2P3. 
At the moment it is  for testing, since only 100GB are available.
server name: ccosvms0219.in2p3.fr:1094 
IPv4 and IPv6 are supported and authentification is based on GSI
To write on tape:  /xrootd/in2p3.fr/tape/dune/
Files are written on tape, and kept on disk as long as there is space.
Of course, in case a file is removed from disk, it is always on tape.
You can also write only on disk  :  /xrootd/in2p3.fr/disk/dune/
Last week I run some basic tests, now, if you have time, you can test also on your side.
Please let me know in case of problems
Thanks, and take care
                          Elisabetta

**Comment by wyuan-uoe** [comment]
`Permission denied` to the xrootd server, 
```
gfal-ls root://ccosvms0219.in2p3.fr:1094/xrootd/in2p3.fr/tape/dune/
gfal-ls error: 13 (Permission denied) - Failed to stat file (Permission denied)
```

I created a GGUS ticket for a solution
https://ggus.eu/index.php?mode=ticket_info&ticket_id=146943

**Comment by wyuan-uoe** [comment]
Feedback from Yvan Calas, this is due to the XRootD bugs, which cannot operate directory listing. Waiting for the bugs fixed. 

In the meantime, there is a new server `ccxrdli283.in2p3.fr:1094` behind the redirector `ccxroot.in2p3.fr:1097` for the node.

**Comment by StevenCTimm** [comment]
Discussion in group meeting--this may be small capacity, need to check 
Steve to send the files that need to be transferred again.
Also this (we think) is a totally different storage eleement to the one that is currently advertised in rucio, need to verify that too.
\

**Comment by wyuan-uoe** [comment]
Test again for xrootd on new server `ccxrdli283.in2p3.fr:1094`. Same as previous, can work on single file, but cannot do directory listing. Same error as Yvan mentioned at https://ggus.eu/index.php?mode=ticket_info&ticket_id=146943.

```
$ xrdcp -d 1 /etc/hostname root://ccxrdli283.in2p3.fr:1094//xrootd/in2p3.fr/disk/dune/hostname
[23B/23B][100%][==================================================][23B/s]

$ xrdfs ccxrdli283.in2p3.fr:1094  stat /xrootd/in2p3.fr/disk/dune/hostname

Path:   /xrootd/in2p3.fr/disk/dune/hostname
Id:     -2305807820546573054
Size:   23
MTime:  2020-09-01 14:46:23
Flags:  48 (IsReadable|IsWritable)

$ xrdfs ccxrdli283.in2p3.fr:1094  stat /xrootd/in2p3.fr/disk/dune/
[ERROR] Server responded with an error: [3010] Stating path '/xrootd/in2p3.fr/disk/dune/' is disallowed.
```

**Comment by StevenCTimm** [comment]
Did you try to the redirector ccxroot.in2p3.fr:1097 to see if it is allowed there?

Steve Timm

**Comment by wyuan-uoe** [comment]
`ccxroot.in2p3.fr:1097` has same outputs as `ccxrdli283.in2p3.fr:1094`.

**Comment by wyuan-uoe** [comment]
Turns out `stat` and `list` files for `subdirectories` under `/xrootd/in2p3.fr/tape/dune/` or `/xrootd/in2p3.fr/disk/dune/` can work.

Now test creating a new RSE `DUNE_FR_CCIN2P3_XROOTD` using `ccxroot.in2p3.fr` and `/xrootd/in2p3.fr/tape/dune/`. I choose the RSE type `DISK` which auto-generating `deterministic` path. The quota set to be 1TB for temporarily. 

```
rucio-admin --account=root rse add DUNE_FR_CCIN2P3_XROOTD

rucio-admin --account=root rse add-protocol --hostname ccxroot.in2p3.fr --scheme root --port 1097 --prefix /xrootd/in2p3.fr/tape/dune/rucio DUNE_FR_CCIN2P3_XROOTD --domain-json '{"wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 1}}'

rucio-admin --account=root rse set-attribute --rse DUNE_FR_CCIN2P3_XROOTD --key fts --value https://fts3-public.cern.ch:8446

rucio-admin --account=root account set-limits dunepro DUNE_FR_CCIN2P3_XROOTD 1TB
``` 

Then test adding one rule `53790edfbee94853973969b58c52025a`

```
rucio --account=dunepro add-rule protodune-dp:np02_photon_run_number_2818 1 DUNE_FR_CCIN2P3_XROOTD
```

All the files can be transferred to `DUNE_FR_CCIN2P3_XROOTD` sucessfully.

**Comment by StevenCTimm** [comment]
It appears that they have not yet been successfully transferred--I attempted to add the 2 rules about the np02 recon 
thing and they are both showing stuck

a6d37b95a6f940f28606f621984d6522  dunepro    protodune-dp:np02_fullrecon_run_number_1407                                              STUCK[0/0/852]          DUNE_FR_CCIN2P3_XROOTD                 1                   2020-10-15 18:44:15
3f67d88a68af45458df47c402e4c98d3  dunepro    protodune-dp:np02_fullrecon_run_number_1415                                              STUCK[0/0/153]          DUNE_FR_CCIN2P3_XROOTD                 1                   2020-10-15 18:44:29

**Comment by wyuan-uoe** [comment]
CERN_PDUNE_EOS, DUNE_FR_CCIN2P3 to DUNE_FR_CCIN2P3_XROOTD can work, but other sites via xrootd stucked.

**Comment by StevenCTimm** [comment]
Robert suggests checking to see that the 3rd party flags for xrdcp are set on both ends, they might not be.
Also suggestion in the meeting that we should be focusing on httpd as main 3rd party transfer

**Comment by StevenCTimm** [comment]
Indeed the 3rd party flag at FNAL_DCACHE  is not enabled for xrootd.  We will have to think about this as it will have implications for transfers to other sites as well.  But since the DUNE_FR_CCIN2P3_XROOTD site supports only xrootd and nothing else we don't have a choice I think.

**Comment by StevenCTimm** [comment]
It's working now, at least for files that are prestaged to disk.  Closing.
