### ISSUE TITLE
Test the INFN storage as given in Matteo's E-mail

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#406]

**Comment by StevenCTimm** [comment]
Tested, It doesn't work, e-mailed back


(rucio129_python3) [dunepro@dunesl7gpvm01 mcruciosam]$ gfal-ls davs://xfer-archive.cr.cnaf.infn.it:8443/dune-grid/dune
gfal-ls error: 1 (Operation not permitted) - HTTP 403 : Permission refused 
(rucio129_python3) [dunepro@dunesl7gpvm01 mcruciosam]$ gfal-copy file:///tmp/1mbtestfile davs://xfer-archive.cr.cnaf.infn.it:8443/dune-grid/dune
Copying file:///tmp/1mbtestfile   [FAILED]  after 1s                            
gfal-copy error: 1 (Operation not permitted) - DESTINATION OVERWRITE   HTTP 403 : Permission refused

**Comment by wyuan-uoe** [comment]
let me know if need me to follow this issue

**Comment by StevenCTimm** [comment]
yes please try.. we have verified that all their voms lsc files are ok now but still everything is failing.

I have forwarded you the e-mail thread.

**Comment by StevenCTimm** [comment]
Works now
Still have to set up an RSE and there is some issue with the storage record reporting for a level above our top level.

**Comment by wyuan-uoe** [comment]
@StevenCTimm, is DUNE_IT_INFN_CNAF a good RSE name for this storage?
