### ISSUE TITLE
Planning--discussion between DM and Workflow--best way to handle output files and best way to handle logs

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#411]
Should logs be shoved into rucio or uploaded to the landscape monitoring where all other log files, stdout and stderr go?

output files--how to handle failures.. there is a fallback but if rucio server is too busy should we have a non-rucio dropbox?

**Comment by wyuan-uoe** [comment]
We had some good examples to analyze logs using `fluentd ` then export matrix to elasticsearch for further monitoring. Happy to test logs if in that case.

**Comment by StevenCTimm** [comment]
WE had the discussion, git issues were open and closed by Andrew.. have decided this way for logs is ok, still not happy about output files but it's what we have.
