### ISSUE TITLE
Add LANCASTER_CEPH RSE

### ISSUE THREAD

**Issue by wyuan-uoe** [DUNE/data-mgmt-ops#413]
Lancaster has a new LANCASTER_CEPH storage to replace old LANCASTER DPM storage. 500TB has been allocated. I'm going to test and add LANCASTER_CEPH RSE to Rucio.

**Comment by StevenCTimm** [comment]
OK.. once that's done and it is working we should then set up a bunch of rules to move everything that's currently at LANCASTER to LANCASTER_CEPH
While doing it could we put a DUNE_UK in the nam,e
i.e. could we call it DUNE_UK_LANCASTER_CEPH?

**Comment by wyuan-uoe** [comment]
I've moved almost everything to DUNE_UK_LANCASTER_CEPH, few files left stuck for both LANCASTER and DUNE_UK_LANCASTER_CEPH,


acb7f979f1c547f9969eee7bfdea3ad7  dunepro    pdsp_mc_reco:PDSPProd4a_MC_1GeV_reco1_sce_datadriven_v1_05                                                                                    SUSPENDED[5690/0/1]          LANCASTER                1                              2021-10-23 00:59:47
113ca123c1d946ae8d54138584a7b60e  dunepro    pdsp_mc_reco:PDSPProd4a_MC_1GeV_reco1_sce_datadriven_v1_05                                                                                    STUCK[5690/0/1]              DUNE_UK_LANCASTER_CEPH   1                              2023-12-10 08:43:03


89a3fa5d301c4e30923c717839b01fc6  dunepro    pdsp_det_reco:PDSPProd4_data_2GeV_reco1_v0                                                                                                    SUSPENDED[10533/0/2]         LANCASTER                1                              2021-10-18 20:16:45
ce91bee556ca490c9a7b5a6e7de0321c  dunepro    pdsp_det_reco:PDSPProd4_data_2GeV_reco1_v0                                                                                                    STUCK[10533/0/2]             DUNE_UK_LANCASTER_CEPH   1                              2023-12-10 08:41:20


a1c7c1a334144029b5c8cd958506e437  dunepro    pdsp_mc_reco:PDSPProd4a_MC_1GeV_reco1_sce_datadriven_v1_08                                                                                    SUSPENDED[8340/0/1]          LANCASTER                1                              2021-10-23 01:02:31
7ac2610e594841849f51b3ff2877ad7a  dunepro    pdsp_mc_reco:PDSPProd4a_MC_1GeV_reco1_sce_datadriven_v1_08                                                                                    STUCK[8340/0/1]              DUNE_UK_LANCASTER_CEPH   1                              2023-12-10 08:38:08


5d33c39675f04917b837ae429277c13d  dunepro    pdsp_mc_reco:PDSPProd4a_MC_3GeV_reco1_sce_off_v1                                                                                              STUCK[31072/0/1]             DUNE_UK_LANCASTER_CEPH   1                              2023-12-10 08:33:23
7ca8e62762844f64ac14ca5dc31db958  dunepro    pdsp_mc_reco:PDSPProd4a_MC_3GeV_reco1_sce_off_v1                                                                                              SUSPENDED[31072/0/1]         LANCASTER                1                              2021-10-23 01:09:11


e6ac0e723b7043fc8884a7225c811f64  dunepro    pdsp_mc_reco:PDSPProd4a_MC_7GeV_reco1_sce_off_v1_09                                                                                           REPLICATING[4112/1/0]        DUNE_UK_LANCASTER_CEPH   1                              2023-12-07 16:07:05
8f6abb3bd1e8403cb0fd2bb484d6c819  dunepro    pdsp_mc_reco:PDSPProd4a_MC_7GeV_reco1_sce_off_v1_09                                                                                           SUSPENDED[4112/0/1]          LANCASTER                1                              2021-10-23 00:00:17


eaaca489440b451daa17cb9bd21e7e0e  dunepro    pdsp_mc_reco:PDSPProd4a_MC_2GeV_reco1_sce_off_v1                                                                                              SUSPENDED[17826/0/78]        LANCASTER                1                              2021-10-23 00:04:54
291b927c680c4fa494032ca6e4825adb  dunepro    pdsp_mc_reco:PDSPProd4a_MC_2GeV_reco1_sce_off_v1                                                                                              REPLICATING[17826/78/0]      DUNE_UK_LANCASTER_CEPH   1                              2023-12-08 08:29:34

**Comment by StevenCTimm** [comment]
I checked one of the files that is trying to get copied from Fermliab to DUNE_UK_LANCASTER_CEPH
It is failing repeatedly due to a checksum error.  Suspect the other ones are too.

**Comment by wyuan-uoe** [comment]
Yes, I checked FTS logs, saw these checksum errors.

**Comment by wyuan-uoe** [comment]
Lancaster people are requesting the shutdown of old DPM due to out of warranty hardware troubles. As everything has moved to new ceph, and the checksum errors rule are identical between old DPM and ceph, @StevenCTimm, I think it's ok to remove old LANCASTER RSE and only working on DUNE_UK_LANCASTER_CEPH?

**Comment by StevenCTimm** [comment]
yes it's ok and the new one seems to be working fine, can we close this ticket?

**Comment by wyuan-uoe** [comment]
yes, close it as completed.
