### ISSUE TITLE
Follow up with Dom Brailsford re FDVDProd1 (CRAB meeting followup)

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#438]
Dom Brailsford says that once fd_mc_2023a VD is there we probably don't have to hold fdvdprod1 on disk anymore

**Comment by StevenCTimm** [comment]
Be sure to ask him this once the reco2 is done.

**Comment by ahiguera-mx** [comment]
Noticed

**Comment by StevenCTimm** [comment]
Dom agreed, we have done this delete.
