### ISSUE TITLE
Parentage--are we specifying it correctly for new files in metacat?  (NO!)

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#498]
Heidi Schellman
  [3:32 PM](https://dunescience.slack.com/archives/C046XB7KAK1/p1708896728814369)
How are people declaring parentage for the reco2 files?  I should be
 "parents": [ {"fid": "abc123"} ]
at the top level for the metadata, NOT core.parents = ….
Not certain if this is a bug in some declaration but can I please look at the scripts people are doing to do this?
Can  people send me an md file from pilot tests in future.    We are going to have to go patch ALL of that metadata to get that parentage in.

**Comment by StevenCTimm** [comment]
For the stuff that's being created in justIN it would be in the scripts that Jake wrote.

**Comment by StevenCTimm** [comment]
[dunepro@dunesl7gpvm01 mcruciosam]$ metacat file show  pdsp_det_reco:np04_raw_run005211_0020_dl8_reco1_42892770_0_20210320T172953Z.root  -l 
checksums:
    adler32   : 048d08ed
    enstore   : 2470381804
    md5       : 57aefe53756df5f78b89b65f7bf2d9cf
created_timestamp   :	2021-03-21 11:03:44.215990+00:00
creator             :	dunepro
fid                 :	52534585
name                :	np04_raw_run005211_0020_dl8_reco1_42892770_0_20210320T172953Z.root
namespace           :	pdsp_det_reco
retired             :	False
retired_by          :	None
retired_timestamp   :	None
size                :	3594642093
updated_by          :	dunepro
updated_timestamp   :	1633446388.70375
parents:
   protodune-sp:np04_raw_run005211_0020_dl8.root (6657843)
children:
   pdsp_det_tuple:np04_raw_run005211_0020_dl8_reco1_42892770_0_20210320T172953Z_michelremoving.root (52534587)
   dune:np04_raw_run005211_0020_dl8_reco1_42892770_0_20210320T172953Z_reco2_49442382_0_20211014T013159Z.root (60451879)


so yes on all the stuff that was ported forward from SAM there is a special "parents" section at top level.
It shouldn't have been core.parents.. if this had gone through the declad it wouldn't have been involved but this was a direct 
declare from JustIN so that's why it worked.

**Comment by hschellman** [comment]
I just tried a (dry-run) update

 metacat file update -d -p fardet-hd:nutau_dune10kt_1x2x6_1107_902_20230826T173935Z_gen_g4_detsim_hitreco.root fardet-hd:nutau_dune10kt_1x2x6_1107_902_20230826T173935Z_gen_g4_detsim_hitreco__20240220T214709Z_reco2.root
 -------- dry run mode --------
 did                 : fardet- hd:nutau_dune10kt_1x2x6_1107_902_20230826T173935Z_gen_g4_detsim_hitreco__20240220T214709Z_reco2.root
 parents             : [{'did': 'fardet-hd:nutau_dune10kt_1x2x6_1107_902_20230826T173935Z_gen_g4_detsim_hitreco.root'}]
 replace             : False
(

so looks like you can do it.  I would need to dig around to figure out a python API for this as it would be better scripted. 

Something that looks over those datasets, finds the parents in the code.parents and adds the real parents.

**Comment by hschellman** [comment]
I think this our first time doing parentage in this production scheme. 

One might be able to get away with:



 over_meta[‘parents'] = [“did”:args.parent] about line 101 in https://github.com/calcuttj/workflow-work/blob/master/convert_metadata.py#L87

but will need to learn how to deal with multiple parents.

**Comment by StevenCTimm** [comment]
Jake has fixed his script so that new files will be done right.  Andrew McNAb has suggested and I agree that we move towards metacat's unified file descriptor which includes both the top level info and the metadata dictionary all in the same json file.. that is how Jake has made the fix for stuff going forward.

**Comment by StevenCTimm** [comment]
Given the ease and speed with which Marc accomplished the change on core.start_time and core.end_time I suggest we consult him and do the change of the older files parentage with postgresql-fu.  Agree?

**Comment by hschellman** [comment]
As long as we are very careful about specification.



On Feb 28, 2024, at 5:48 AM, Steven Timm ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


Given the ease and speed with which Marc accomplished the change on core.start_time and core.end_time I suggest we consult him and do the change of the older files parentage with postgresql-fu. Agree?

**Comment by hschellman** [comment]
An issue for the parents conversion.  the existing parents info in the files does not have the namespace - it is only the filename in some cases.  Reco2 output does,  reco3_ana does not.  

So one can probably do a db patch for reco but not for ana files. 



metacat file show -m fardet-vd:nu_dunevd10kt_1x8x6_3view_30deg_958_89_20230803T211556Z_gen_g4_detsim_hitreco__20240220T114634Z_reco2.root

core.parents    : [{‘file_name’: ‘fardet-vd:nu_dunevd10kt_1x8x6_3view_30deg_958_89_20230803T211556Z_gen_g4_detsim_hitreco.root’}]


metacat file show -m fardet-vd:nu_dunevd10kt_1x8x6_3view_30deg_958_89_20230803T211556Z_gen_g4_detsim_hitreco__20240220T114634Z_reco2_ana.root

core.parents    : [{‘file_name’: ‘nu_dunevd10kt_1x8x6_3view_30deg_958_89_20230803T211556Z_gen_g4_detsim_hitreco__20240220T114634Z_reco2.root’}]

**Comment by StevenCTimm** [comment]
Fixed now, closing.
