### ISSUE TITLE
One file stuck when transfer file to RAL_ECHO

### ISSUE THREAD

**Issue by wyuan-uoe** [DUNE/data-mgmt-ops#5]
There is one file still stuck for rule `5de0d532f18e4eabb6af99f4525c801c`  for transfer datasets    `np04_pdspprod2_mc:PDSPProd2_MC_1GeV_reco_sce_off` to `RAL_ECHO`.

The error message said the file `np04_pdspprod2_mc:PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root` can not be found. 

But it should be on: `FNAL_DCACHE: root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/dune//tape_backed/dunepro/physics/full-reconstructed/2019/mc/out1/PDSPProd2/22/67/27/07/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root`

I also cannot download this file using `rucio get` CLI.

**Comment by StevenCTimm** [comment]
OK I will check.

**Comment by StevenCTimm** [comment]
It's not there--it appears that this was one of the files that was declared bad after the rucio data set was made.  I will look a bit more but probably the right thing to do is to remove this one file declaration from the rucio data set.

**Comment by wyuan-uoe** [comment]
@StevenCTimm, so it means using `Rucio erase dids` to remove this file?

**Comment by StevenCTimm** [comment]
So what we have to do first is to remove the file from the data set.  But to do that we have to figure out what data set it is part of because 
np04_pdspprod2_mc:PDSPProd2_MC_1GeV_reco_sce_off is a container that contains a lot of data sets.

Find which dataset it is part of by rucio list-parent-datasets
then remove the file from the data set by rucio detach

That should set the rule to ok

Then declare the replica as bad.
with rucio-admin replicas declare-bad

**Comment by wyuan-uoe** [comment]
OK, I detached this file,
```
rucio list-parent-datasets np04_pdspprod2_mc:PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root
+-----------------------------------------------------+--------------+
| SCOPE:NAME                                          | [DID TYPE]   |
|-----------------------------------------------------+--------------|
| np04_pdspprod2_mc:np04_pdspprod2_mc.run22672707.off | DATASET      |
+-----------------------------------------------------+--------------+

rucio_client_sl7]$ rucio detach np04_pdspprod2_mc:np04_pdspprod2_mc.run22672707.off np04_pdspprod2_mc:PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root
DIDs successfully detached from np04_pdspprod2_mc:np04_pdspprod2_mc.run22672707.off
```

But I cannot declare the replica as bad, 
```
rucio-admin --account=root replicas declare-bad np04_pdspprod2_mc:PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root --reason 'file not found'
An unknown exception occurred.
Details: ERROR, multiple matches : root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/dune//tape_backed/dunepro/physics/full-reconstructed/2019/mc/out1/PDSPProd2/22/67/27/07/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root at FNAL_DCACHE_STAGING
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
  File "/dune/app/home/dunepro/rucio_client_sl7/bin/rucio-admin", line 125, in new_funct
    return function(*args, **kwargs)
  File "/dune/app/home/dunepro/rucio_client_sl7/bin/rucio-admin", line 929, in declare_bad_file_replicas
    non_declared = client.declare_bad_file_replicas(pfns=chunk, reason=args.reason)
  File "/dune/app/home/dunepro/rucio_client_sl7/lib/python2.7/site-packages/rucio/client/replicaclient.py", line 61, in declare_bad_file_replicas
    raise exc_cls(exc_msg)
RucioException: An unknown exception occurred.
Details: ERROR, multiple matches : root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/dune//tape_backed/dunepro/physics/full-reconstructed/2019/mc/out1/PDSPProd2/22/67/27/07/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root at FNAL_DCACHE_STAGING
```
 the pnf of this file used for both FNAL_DCACHE and FNAL_DCACHE_STAGING.

**Comment by StevenCTimm** [comment]
Whenever I have done a replicas declare-bad I have used the PFN
root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/dune//tape_backed/dunepro/physics/full-reconstructed/2019/mc/out1/PDSPProd2/22/67/27/07/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root
in the declare-bad command.

Try that,.
'

**Comment by aheavey** [comment]
Hi Steve,
I don’t know how I got on this list, and it doesn’t look like a regular listserv. Do you know how I can get removed from it?
-Anne

**Comment by wyuan-uoe** [comment]
The same error.

```
rucio_client_sl7]$ rucio-admin --account=root replicas declare-bad root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/dune//tape_backed/dunepro/physics/full-reconstructed/2019/mc/out1/PDSPProd2/22/67/27/07/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root  --reason 'file not found'
An unknown exception occurred.
Details: ERROR, multiple matches : root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/dune//tape_backed/dunepro/physics/full-reconstructed/2019/mc/out1/PDSPProd2/22/67/27/07/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root at FNAL_DCACHE_STAGING
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
  File "/dune/app/home/dunepro/rucio_client_sl7/bin/rucio-admin", line 125, in new_funct
    return function(*args, **kwargs)
  File "/dune/app/home/dunepro/rucio_client_sl7/bin/rucio-admin", line 929, in declare_bad_file_replicas
    non_declared = client.declare_bad_file_replicas(pfns=chunk, reason=args.reason)
  File "/dune/app/home/dunepro/rucio_client_sl7/lib/python2.7/site-packages/rucio/client/replicaclient.py", line 61, in declare_bad_file_replicas
    raise exc_cls(exc_msg)
RucioException: An unknown exception occurred.
Details: ERROR, multiple matches : root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/dune//tape_backed/dunepro/physics/full-reconstructed/2019/mc/out1/PDSPProd2/22/67/27/07/PDSPProd2_protoDUNE_sp_reco_35ms_sce_off_23530731_0_7bae343a-bafa-49a7-b689-1a462272db49.root at FNAL_DCACHE_STAGING
```

**Comment by StevenCTimm** [comment]
I filed issue INC000001097859 with data management support we will see what they say.

**Comment by StevenCTimm** [comment]
From Brandon White:
BW
Brandon White
Additional comments (customer communication)•2020-04-27 16:12:26
I updated the file replica manually to the bad state, and I think that should do the trick.

Now no replicas show for this file.

The rule no longer shows as STUCK

**Comment by bjwhite-fnal** [comment]
Ok, I'm glad that the judge-evaluator eventually picked that up @StevenCTimm, and I see it also. I'll close out the ticket on our end.

**Comment by wyuan-uoe** [comment]
Thanks @bjwhite-fnal, this issue solved and I close it.
