### ISSUE TITLE
Investigate the new JustIN mode of per-RSE data sets

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#566]
JustIN now allows for automated creation of datasets on a per-RSE basis.. this would give us better visibility into where the data is coming from on Rucio rules but at the cost of us having to make the rules manually to get everything back home.. need to understand the implications.. would also have the side effect of not leaving rule-less replicas all over the world and filling up the world with stuff that can't be deleted until a tombstone is set.

**Comment by dougbenjamin** [comment]
we need justIN to create the datasets (or Rules) to bring the data back to FNAL

**Comment by StevenCTimm** [comment]
Justin 1.01 was deployed without the rules coming back to FNAL.  Andrew is considering a request to add that back.

**Comment by StevenCTimm** [comment]
Closing this, will file a justIN issue instead.. believe I understand what's going on with the current version and have documented for myself and others what to do.
