### ISSUE TITLE
Data Challenge: RSE Prep: create new DUNE_CERN_EOS RSE, deterministic, rw. 

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#60]
Have to coordinate with NP02 and NP04 to make this happen

**Comment by StevenCTimm** [comment]
Should be called DUNE_CERN_EOS
Should be rw and deterministic
support https and xrootd protocols for lan and wan including TPC
should be based on /eos/experiment/neutplatform/protodune/dune directory
Should have bidirectional distances to FNAL_DCACHE, FNAL_DCACHE_TEST, DUNE_US_BNL_SDCC, and
all European RSE's that are active plus the other two CERN RSEs

**Comment by dougbenjamin** [comment]
(rucio126_python3) [dunepro@dunesl7gpvm01 ~]$ rucio-admin rse info DUNE_CERN_EOS
Settings:
=========
  availability_delete: True
  availability_read: True
  availability_write: True
  credentials: None
  delete_protocol: 1
  deterministic: True
  domain: ['lan', 'wan']
  id: 765b276ce29c49bd8227fd4fc9ca5431
  lfn2pfn_algorithm: hash
  qos_class: None
  read_protocol: 1
  rse: DUNE_CERN_EOS
  rse_type: DISK
  sign_url: None
  staging_area: False
  third_party_copy_protocol: 1
  verify_checksum: True
  volatile: False
  write_protocol: 1
Attributes:
===========
  DUNE_CERN_EOS: True
  country: CH
  fts: https://fts3-public.cern.ch:8446
  site: CERN
Protocols:
==========
  https
    domains: '{"lan": {"read": 1, "write": 1, "delete": 1}, "wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 1}}'
    extended_attributes: None
    hostname: eospublic.cern.ch
    impl: rucio.rse.protocols.gfalv2.Default
    port: 0
    prefix: /eos/experiment/neutplatform/protodune/dune
    scheme: https
  root
    domains: '{"lan": {"read": 1, "write": 2, "delete": 1}, "wan": {"read": 1, "write": 2, "delete": 1, "third_party_copy": 10}}'
    extended_attributes: None
    hostname: eospublic.cern.ch
    impl: rucio.rse.protocols.gfalv2.Default
    port: 0
    prefix: /eos/experiment/neutplatform/protodune/dune
    scheme: root
Usage:
======
  rucio
    files: 0
    free: None
    rse: DUNE_CERN_EOS
    rse_id: 765b276ce29c49bd8227fd4fc9ca5431
    source: rucio
    total: 0
    updated_at: 2022-04-19 13:36:39
    used: 0
RSE limits:
===========

**Comment by StevenCTimm** [comment]
This is done.
