### ISSUE TITLE
Understand difference between rucio list-account-usage and "rucio" value in storage json.  (esp. at QMUL where rucio number is higher)

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#602]
Aaron showed that rucio list-account-usage for user dunepro on some RSEs are 200TB less than the total value of
rucio storage on a site, need to investigate.  think it's replicas not associated with any given Rule but should be sure of that.

**Comment by wyuan-uoe** [comment]
I checked QMUL, both list-account-usage and srr show QMUL usage is less then 800TB, but rucio number shows 936TB. 

Comparing the rucio db record with dump file list, lots of files exist in rucio db but not found on site, the files list:
/exp/dune/app/users/wyuan/dumps_check/outputs

**Comment by StevenCTimm** [comment]
so one thing is sure:  rucio list-account-usage shows only those things which are corresponding to rules.

The fact that rucio is showing more I think is that rucio is complaining that there's no delete method assigned for QMUL so rucio thinks the deletes are not happening.  Have to look at which daemon is throwing this error and if it's still happening.
(reaper, probably).

**Comment by StevenCTimm** [comment]
Closing this.. the delete method issue was fixed, the rucio and non-rucio numbers at QMUL converged although still not totally understood.. will re-visit this once QMUL comes online in September.
