### ISSUE TITLE
still some bad metadata in workflow 1777, tape copy not going clean.

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#611]
Most of the other core.start_times and core.end_times were fixed but half of this workflow was not.

-----------------------+-----------------+
[dunepro@duneopsgpvm01 mcruciosam]$ metacat file show fardet-vd:nu_numu2nue_nue2nutau_dunevd10kt_1x8x6_3view_30deg_994_113_20230808T031551Z_gen_g4_detsim_hitreco__20240406T205455Z_reco2_Pandora_Events.pndr   -m -j
{
    "checksums": {
        "adler32": "f141d8b4"
    },
    "created_timestamp": 1712438352.807821,
    "creator": "dunepro",
    "fid": "CIePkdCKSieyyDcV",
    "metadata": {
        "art.first_event": 11301,
        "art.last_event": 11400,
        "art.process_name": "Reco2",
        "core.application": "art.reco2",
        "core.application.family": "art",
        "core.application.name": "reco2",
        "core.application.version": "v09_81_00d02",
        "core.data_stream": "out1",
        "core.data_tier": "pandora-info",
        "core.end_time": "2024-04-06T21:04:19",
        "core.event_count": 100,
        "core.file_format": "binary",
        "core.file_type": "mc",
        "core.first_event_number": 11301,
        "core.group": "dune",
        "core.last_event_number": 11400,
        "core.parents": [
            {
                "file_name": "fardet-vd:nu_numu2nue_nue2nutau_dunevd10kt_1x8x6_3view_30deg_994_113_20230808T031551Z_gen_g4_detsim_hitreco.root"
            }
        ],
        "core.run_type": "fardet-vd",
        "core.runs": [
            994
        ],
        "core.runs_subruns": [
            99400001
        ],
        "core.start_time": "2024-04-06T20:55:52",
        "dune.campaign": "fd_mc_2023a_reco2",
        "dune.config_file": "reco2_dunevd10kt_nu_1x8x6_3view_30deg_geov3.fcl",
        "dune.output_status": "confirmed",
        "dune.requestid": "ritm1780305",
        "dune.workflow": {
            "cpuinfo": "AMD EPYC 7702P 64-Core Processor",
            "hostname": "wn1205080.tier2.hep.manchester.ac.uk",
            "job_id": "6018.44@justin-prod-sched02.dune.hep.ac.uk",
            "jobscript_cpu_seconds": 0,
            "jobscript_finish": 1712437499,
            "jobscript_real_seconds": 0,
            "jobscript_start": 1712436866,
            "os_release": "Scientific Linux release 7.9 (Nitrogen)",
            "site_name": "UK_Manchester",
            "stage_id": 1,
            "user": "benjamin@fnal.gov",
            "workflow_id": 1777
        },
        "dune_mc.detector_type": "fardet-vd",
        "dune_mc.gen_fcl_filename": "prodgenie_nu_numu2nue_nue2nutau_dunevd10kt_1x8x6_3view_30deg.fcl"
    },
    "name": "nu_numu2nue_nue2nutau_dunevd10kt_1x8x6_3view_30deg_994_113_20230808T031551Z_gen_g4_detsim_hitreco__20240406T205455Z_reco2_Pandora_Events.pndr",
    "namespace": "fardet-vd",
    "retired": false,
    "retired_by": null,
    "retired_timestamp": null,
    "size": 34816378,
    "updated_by": "dunepro",
    "updated_timestamp": 1712612234.01853
}

**Comment by dougbenjamin** [comment]
all core.end_time and core.start_time metadata converted to float from string or int

**Comment by dougbenjamin** [comment]
fixed after several passes through because of transfer timeout and partial transfers from Metacat
