### ISSUE TITLE
Are the fardet-hd reco and fardet-vd reco MetaCat datasets and corresponding Rucio rules up to date

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#642]
Metacat datasets haven't been modified since 2024-04-04.. the cleanup. workflows 1769-1781 were run since then.
Thought these were included in a new round of metacat datasets but these datasets don't appear to be there, 
nor for the case of the fardet-vd are there any disk replicas in Europe.
The existing rucio rules, like most of the others, are built up of datasets that don't include the 1769-1781 datasets.
Have asked Aaron about this.  Won't delete the fardet-vd off of disk  at DUNE_US_FNAL_DISK_STAGE until we have an answer

**Comment by StevenCTimm** [comment]
As expected the fardet-hd stuff (workflows 1769-1774) haven't been added to the corresponding fardet-hd official datasets or the official rucio containers either, and there are no rules to send it anywhere other than DUNE_US_FNAL_DISK_STAGE

**Comment by StevenCTimm** [comment]
Much of the reco2 files from fardet-hd already exist only on FNAL_DCACHE by rule, we had removed most of them from DUNE_US_FNAL_DISK_STAGE but there are a few that I'll clean up now.

**Comment by StevenCTimm** [comment]
Deleted 57TB of fardet-hd reco2 files off of DUNE_US_FNAL_DISK_STAGE

**Comment by StevenCTimm** [comment]
adding rules to copy all the fardet-vd reco files currently on DUNE_US_FNAL_DISK_STAGE to SURFSARA

**Comment by StevenCTimm** [comment]
Aaron says he was holding re-spinning these data sets until such time as he heard from me re. the last problems in the data set.  These should be fixed by tomorrow night and I will notify him when they are.  see https://github.com/DUNE/data-mgmt-ops/issues/611 re the problem with set 1777

**Comment by ahiguera-mx** [comment]
Hi @StevenCTimm 
Should I proceed with the creation of the new version of datasets? and the corresponding Rucio container?

**Comment by StevenCTimm** [comment]
We did fix the metadata and get all the files to tape in workflow 1777.
There are still probably some files in metacat in that dataset that don't have rucio replicas that need to be cleaned up.

See issue #648.  I would delay this one a bit unless the fardet people really want it.

**Comment by ahiguera-mx** [comment]
Ok, I will hold on to this then, no urgency from sim/reco side

**Comment by ahiguera-mx** [comment]
Hi @StevenCTimm  
The v2_official dataset and corresponding rucio containers have been updated with the additional workflows
see, e.g. https://metacat.fnal.gov:9443/dune_meta_prod/app/gui/datasets?selection=all&namematch=v2_official&submit=Submit
