### ISSUE TITLE
Investigate if we can put a cap from the rucio end on given rucio activities.

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#658]

**Comment by StevenCTimm** [comment]
In particular the DAQ activity that we're going to create.

**Comment by StevenCTimm** [comment]
[RITM2157673](https://fermi.servicenowservices.com/sc_req_item.do?sys_id=9079d22d4797ca509fddbd51026d43d4&sysparm_view=ess&sysparm_record_target=sc_req_item&sysparm_record_row=3&sysparm_record_rows=17&sysparm_record_list=active%3Dtrue%5Erequest.requested_forDYNAMIC107a23f36f9c394032544d1fde3ee43b%5Erequest.requested_for%3D32b4c7270a0a3c590054cb9fd2a1c689%5EORrequest.requested_for.manager%3D32b4c7270a0a3c590054cb9fd2a1c689%5EORcat_item%21%3D0366e9a11b3ae01084150e9ee54bcb86%5Eu_security_related%3Dfalse%5EORwatch_listCONTAINS32b4c7270a0a3c590054cb9fd2a1c689%5EORDERBYDESCzztextsearchyy)

has been filed to get the activities created in rucio.
Once that is done we can approach the FTS3 admins to put different weights on them
and let the CTA admins know we have done so.

**Comment by yuyiguo** [comment]
We opened a CERN ticket to ask the FTS3 admins to put different weights on activities.
https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillment&n=RQF2738922
