### ISSUE TITLE
Test Manchester new cephfs RSE

### ISSUE THREAD

**Issue by wyuan-uoe** [DUNE/data-mgmt-ops#697]
Manchester has a new storage is a cephfs + xrootd gateways like Lancaster has.

There is a ticket to update it since ATLAS is keeping it open.
https://ggus.eu/index.php?mode=ticket_info&ticket_id=158830

The end points are
https://meitner.tier2.hep.manchester.ac.uk:1094/cephfs/experiments/dune
root://meitner.tier2.hep.manchester.ac.uk:1094/cephfs/experiments/dune

I'll be testing it and add it to Rucio then

**Comment by wyuan-uoe** [comment]
I've added this new RSE as DUNE_UK_MANCHESTER_CEPH, and duplicating the rules from old MANCHESTER RSE to this new one.

Now there is an issue about low transfer rate (~40MiB/s) on the DUNE_UK_MANCHESTER_CEPH. Manchester site will shutdown few days to fix an initial misconfiguration.

**Comment by StevenCTimm** [comment]
So it looks like there are only half as many rules on DUNE_UK_MANCHESTER_CEPH as there are on MANCHESTER
(leaving out the empty workflow-specific ones).

Are we going to get the rest of the ones over there?

**Comment by wyuan-uoe** [comment]
Yes, I'm adding few of the rest rules to DUNE_UK_MANCHESTER_CEPH to see the status. If the transfers are stable, the rest rules will be added, otherwise, we have to wait for the further configs from the site.

**Comment by StevenCTimm** [comment]
This is now done
