### ISSUE TITLE
Rucio add-user script is missing some new users

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#715]
Megan wrobel (mwrobel) wasn't automatically added, have added her but have to ask Dennis Lee what is going on.

**Comment by d-ylee** [comment]
@StevenCTimm The DN for the DUNE production server didn't have read-only access to FERRY. After having the DN added, the script was able to run and add users.

Please ask Megan to try again. I believe her account and DN have been added to the DUNE production cluster.

**Comment by StevenCTimm** [comment]
OK closing this..
Thanks
