### ISSUE TITLE
move 100 TB off of PIC

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#723]
They want to reserve 100TB for local use of their group.

**Comment by wyuan-uoe** [comment]
Can we move the data to Glasgow?

**Comment by StevenCTimm** [comment]
data was moved to DUNE_UK_MANCHESTER_CEPH
Took a while because at first we didn't have a distance defined between that and DUNE_ES_PIC but we do now
Data has been moved, I have deleted the corresponding rules at DUNE_ES_PIC, we should see deletion happen in about 45 minutes.
