### ISSUE TITLE
Issue with submitMerge.py for chunk files

### ISSUE THREAD

**Issue by ahiguera-mx** [DUNE/data-mgmt-ops#747]
`submitMerge.py` does not properly handle cases where the number of files is not perfectly divisible by the chunk size
These lines need to be modified 

https://github.com/DUNE/data-mgmt-ops/blob/eaf287b0b838f948b4751f541a11a57a9d95d1cc/utilities/merging/submitMerge.py#L200-L207

**Comment by hschellman** [comment]
Can you give me an example - I think it's an edge case.  I certainly have run over samples which are not multiples but there may be an N-1 case.   It would be good to have an exact thing to check.

**Comment by hschellman** [comment]
/pnfs/dune/scratch/users/schellma/merging/run_0000028005_000000_000100_20241018181229 is an example
64 files in, chunk = 50, does 50+14

but yes, might be a strange case with 1 left over file at the end.

**Comment by ahiguera-mx** [comment]
So I ran the example with the following values 

```
export SKIP=0  
export CHUNK=20 
export NFILES=50 
```

I ended up processing 80 files, where each merging file has 20 files. Should not this process only 50 files? Where the output should be 3 files, where 2 files shuold have 20 files merged, and 1 file with 10 files merged?

**Comment by ahiguera-mx** [comment]
my example can be found at `/pnfs/dune/scratch/users/higuera/merging/fardet-vd_0_50_cafmaker_dunevd10kt_1x8x6_3view_30deg_runreco-nuenergy_geov3.fcl_20241018T154226
`

**Comment by hschellman** [comment]
Yep that looks like an issue.

I will do your changes as I think my changes are earlier (in file finding)

On Oct 18, 2024, at 4:51 PM, Aaron Higuera ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


So I ran the example with the following values

export SKIP=0
export CHUNK=20
export NFILES=50


I ended up processing 80 files, where each merging file has 20 files. Should not this process only 50 files? Where the output should be 3 files, where 2 files shuold have 20 files merged, and 1 file with 10 files merged?

**Comment by hschellman** [comment]
Which example?

On Oct 18, 2024, at 5:48 PM, Schellman, Heidi ***@***.***> wrote:

Yep that looks like an issue.

I will do your changes as I think my changes are earlier (in file finding)

On Oct 18, 2024, at 4:51 PM, Aaron Higuera ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


So I ran the example with the following values

export SKIP=0
export CHUNK=20
export NFILES=50


I ended up processing 80 files, where each merging file has 20 files. Should not this process only 50 files? Where the output should be 3 files, where 2 files shuold have 20 files merged, and 1 file with 10 files merged?

**Comment by ahiguera-mx** [comment]
I ran `examples/makeCAF.sh` 
I will hold off on this until you finish the testing for the tarballing

**Comment by ahiguera-mx** [comment]
@hschellman 
I have fixed the logic in `mergeRoot.py` to account for the number of chunks and chunk size given the number of files to process and skip files. Then, the corresponding scripts were modified to propagate these changes. I test this with interactiveRun, makeCaf and with a list of files. My branch includes your latest improvements from HMS-SEP24, so in principle, we can merge this in the master. 
Could you have a look and run your test to see if everything works

**Comment by ahiguera-mx** [comment]
We have merge changes, so this has been fixed
