### ISSUE TITLE
rucio v36 vs rucio v35 different format for policy package

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#787]
from mattermost

Maximilian Linhoff
[8:36 AM](https://mattermost.web.cern.ch/rucio/pl/sxosocrjwig1zx8rrgbnzrq8qa)
or policy package operators: Rucio 36 includes a breaking change in the way the supported Rucio version is configured. 
That makes it impossible to have a plugin that's compatible with 35 and 36, right?
[8:36 AM](https://mattermost.web.cern.ch/rucio/pl/bdcpjyd7up85uge3c64aw9hnoa)
Because 35 won't understand the new format

	
Martin Barisits
[8:42 AM](https://mattermost.web.cern.ch/rucio/pl/d5cjjk3i33d3mjd8c7b644ny1a)
You will need two different version of the policy package for this yes. They can both still hold the exact same plugin and are identical in any way, other than the version specifier.

**Comment by jamesp-epcc** [comment]
I have updated the DUNE policy package for the new format used in v36. Links to both versions below.

Version 35 compatible - https://github.com/jamesp-epcc/DUNERucioPolicy/releases/tag/rucio35b
Version 36 compatible - https://github.com/jamesp-epcc/DUNERucioPolicy/releases/tag/rucio36

**Comment by StevenCTimm** [comment]
James fixed this, closed.
