### ISSUE TITLE
Onboard PIC as a new Rucio Storage element

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#87]
They have 500 TB.  Current question on network connectivity from their staff

**Comment by StevenCTimm** [comment]
manual fts-transfer-submit works, rucio transfer does not yet.. have to figure out why.

**Comment by StevenCTimm** [comment]
contacts are Elena Planas.  eplanas@pic.es   and Gonzalo Merino. merino@pic.es

**Comment by wyuan-uoe** [comment]
PIC RSE works now, `rucio upload` from PIC works as well.
